FROM python:3.9-slim-bullseye as build

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY scripts/* /app/
COPY ./requirements-armv7.txt /tmp/requirements-armv7.txt

RUN apt-get --allow-releaseinfo-change update \
    && apt-get install -y --no-install-recommends jq chromium curl chromium-driver tzdata \
    && apt-get install libgl1-mesa-glx libglib2.0-0 -y \
    && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN cd /tmp \
    && pip config --global set global.extra-index-url https://www.piwheels.org/simple \
    && python3 -m pip install --upgrade pip \
    && curl -O -L https://github.com/nknytk/built-onnxruntime-for-raspberrypi-linux/raw/master/wheels/buster/onnxruntime-1.8.1-cp39-cp39-linux_armv7l.whl \
    && PIP_ROOT_USER_ACTION=ignore pip3 install onnxruntime-1.8.1-cp39-cp39-linux_armv7l.whl \
    && PIP_ROOT_USER_ACTION=ignore pip3 install \
    --disable-pip-version-check \
    --no-cache-dir \
    -r requirements-armv7.txt \
    && rm -rf /tmp/* \
    && pip cache purge \
    && rm -rf /var/log/*


ENV LANG C.UTF-8

CMD ["python"]